# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e5394583913b8bf8a8f75b33eaef91b6dbc3ac90993ffc7046f4b29a639e055cfa02bc897f5378354e239d1915a4dda4cd6bb10205ad776ffb592472d45a43e

test:
  secret_key_base: 8edf7c97ade6d28accb0c12de204f4c3a7b0b7819dbf5ceb80cd7a4bbe011cbd94c2186ef851c05cb33f9c4770d1e28f8fe56d780c3031c08aee1ea161cabfd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
